# Generated by Django 4.2.1 on 2024-04-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер команды')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название команды')),
                ('total_score', models.IntegerField(default=0, verbose_name='Счёт команды')),
            ],
        ),
    ]
